/opt/gridpack/lib
/opt/cudss/lib
/usr/local/cuda/targets/sbsa-linux/lib
/usr/local/nvidia/lib
/usr/local/nvidia/lib64
/deps/boost-1.81.0/install_for_gridpack/lib
/deps/ga-5.9.1/install_for_gridpack/lib
/deps/petsc/install_for_gridpack/lib
/usr/lib/aarch64-linux-gnu/openmpi/lib
